set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(RK3568_PACK "/opt/rk3568_kernel_pack")
set(RK3568_TOOLCHAIN_ROOT "${RK3568_PACK}/toolchain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu")
set(RK3568_SYSROOT "${RK3568_PACK}/sysroot")
set(QT_HOST_PATH "/opt/Qt/6.10.3")
set(QT_TARGET_PATH "/opt/Qt/6.10.3-rk3568-aarch64")

set(CMAKE_C_COMPILER "${RK3568_TOOLCHAIN_ROOT}/bin/aarch64-none-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${RK3568_TOOLCHAIN_ROOT}/bin/aarch64-none-linux-gnu-g++")
set(CMAKE_SYSROOT "${RK3568_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH
    "${RK3568_SYSROOT}"
    "${QT_TARGET_PATH}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_PREFIX_PATH "${QT_TARGET_PATH}")
set(QT_HOST_PATH "${QT_HOST_PATH}" CACHE PATH "Host Qt path")
set(QT_HOST_PATH_CMAKE_DIR "${QT_HOST_PATH}/lib/cmake" CACHE PATH "Host Qt CMake package path")

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${RK3568_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${RK3568_SYSROOT}/usr/lib/pkgconfig:${RK3568_SYSROOT}/usr/share/pkgconfig")
